### ISSUE TITLE
[🐛 Bug Report]: Electrostatic Ray to Prickly Personality Bug

### ISSUE THREAD

**Issue by sinichi1213** [FoonieMagus/ApeironBattleDemo_IssueList#100]
### Demo Environment

Production

### Battle Demo Version

0.5.147

### System Environment

OS: Windows 10 Pro
CPU: AMD Ryzen 5 2400g
GPU: NVIDIA RTX 2060

### What is expected?

The delay reflect damage must be accurate and the damage reflect must not take longer than expected,

### What is happening?

The laser is continuously reflecting damage from prickly even though you are not targeting the guardian. 

Here's the video of the bug.

https://drive.google.com/file/d/1adVqn5ozU6Wsc95JZLn1NnLCuf-ufpKK/view?usp=sharing

### Reproducible Bugs

It's abusable when the enemy use the prickly and you can't escape the damage.

### Related link

https://drive.google.com/file/d/1adVqn5ozU6Wsc95JZLn1NnLCuf-ufpKK/view?usp=sharing

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/issues?q=label%3Abug) to ensure this bug has not already been reported

### No personal information provided

- [X] I confirm that I have not provided any personal information such as my wallet address or email address in this contribution.

### Open ticket if needed

- [X] In the event that personal information is required, I understand that I am expected to open a ticket in the [Discord](https://discord.gg/apeiron-doodaria) channel and reference the specific issue on Github.

**Comment by EmberLeung** [comment]
![image](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/assets/99469194/d3bcc11e-5d8b-43bd-9325-84d72fbec94a)
In the 4019 upgrade 2 feature, when the Electrostatic Ray hit a enemy, it will apply a status effect that will deal damage per 0.5 second. The status effect life time is Electrostatic Ray left time (When Electrostatic Ray Cancel it also alive). The damage action will trigger the guardian's Prickly reflecting damage.
