### ISSUE TITLE
[🐛 Bug Report]: Frostbite water damage damage store lower than expected

### ISSUE THREAD

**Issue by tanbod** [FoonieMagus/ApeironBattleDemo_IssueList#106]
### Demo Environment

Beta Test

### Battle Demo Version

0.5.157

### System Environment

Device name LAPTOP-PQL4Q8OR
Processor 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz 2.30 GHz
Installed RAM 32.0 GB (31.8 GB usable)
Device ID 960547AC-A53F-4F30-922C-6C6E35012C91
Product ID 00327-35933-61019-AAOEM
System type 64-bit operating system, x64-based processor
windows 10

### What is expected?

frost bite should store 50 % from water damage and 25% from other damage type

### What is happening?

from video i provide it look like currently it store around 32.82 % from water damage
first dragon beam damage done is 1064
second water ritual damage done is 968
third dragon beam damage done is 1064
sum up is 3096 
frostbite damage is 1016

### Reproducible Bugs

every time

### Related link

https://drive.google.com/file/d/1oxoTH3MtHMlt1-bu5Mex6w0d8m77qrRV/view?usp=drive_link

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/issues?q=label%3Abug) to ensure this bug has not already been reported

### No personal information provided

- [X] I confirm that I have not provided any personal information such as my wallet address or email address in this contribution.

### Open ticket if needed

- [X] In the event that personal information is required, I understand that I am expected to open a ticket in the [Discord](https://discord.gg/apeiron-doodaria) channel and reference the specific issue on Github.

**Comment by emberwaynek** [comment]
0:20 Frostbite started
0:22 dragon beam damage (Water) 1064
0:23 Opponent dash back inside coldwater core's area, frostbite is full-stacked, frostbite damage = 1064 * 0.5 = 532. 
Another Frostbite started.
0:25 coldwater core detonation damage (Water) 968
0:26 dragon beam damage (Water) 1064
0:35 Frostbite expired. frostbite damage =  (968 * 0.5 + 1064 * 0.5) =  1016

**Comment by tanbod** [comment]
ohh my bad this one
