### ISSUE TITLE
[🐛 Bug Report]: Apeiron MP account doesn't match App

### ISSUE THREAD

**Issue by MarkL-0** [FoonieMagus/ApeironBattleDemo_IssueList#119]
### Demo Environment

Production

### Battle Demo Version

v.0.5.173

### System Environment

Win11

### What is expected?

Same user credentials to work both on Apeiron MP and Staging App

### What is happening?

Changed password in MP but says incorrect password. Found out that it's still using the old password. The new password is not syncing with the app account.

Account:
za.trezor+2@gmail.com

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/issues?q=label%3Abug) to ensure this bug has not already been reported

### No personal information provided

- [X] I confirm that I have not provided any personal information such as my wallet address or email address in this contribution.

### Open ticket if needed

- [X] In the event that personal information is required, I understand that I am expected to open a ticket in the [Discord](https://discord.gg/apeiron-doodaria) channel and reference the specific issue on Github.

**Comment by gemscng** [comment]
not a bug. It is staging server. changing in production will not affect staging server account.
