### ISSUE TITLE
[🐛 Bug Report]: Tutorial display bug in Japanese

### ISSUE THREAD

**Issue by doetto** [FoonieMagus/ApeironBattleDemo_IssueList#120]
### Demo Environment

Production

### Battle Demo Version

v0.5.186 c41e06f

### System Environment

OS:Windows 11 Home 64-bit (10.0, Build 22621)
GPU:NVIDIA GeForce RTX 4060 Ti
CPU:13th Gen Intel(R) Core(TM) i5-13400F (16 CPUs), ~2.5GHz

### What is expected?

Problem with display when language setting is set to Japanese

### What is happening?

If the language setting is set to Japanese, Fritz's lines will be blank in the tutorial.

### Additional info

![2024-02-28 (1)](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/assets/135049720/5b2bdcf0-b225-4ccd-a98f-58f41b1933c7)
![2024-02-29 (1)](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/assets/135049720/adf67e4f-ea05-4d79-a0c0-45ad23ee3cef)

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/issues?q=label%3Abug) to ensure this bug has not already been reported

### No personal information provided

- [X] I confirm that I have not provided any personal information such as my wallet address or email address in this contribution.

### Open ticket if needed

- [X] In the event that personal information is required, I understand that I am expected to open a ticket in the [Discord](https://discord.gg/apeiron-doodaria) channel and reference the specific issue on Github.

**Comment by gemscng** [comment]
should showing english right now. @doetto  please check
