### ISSUE TITLE
FC6 volcano bug[🐛 Bug Report]: 

### ISSUE THREAD

**Issue by DamonHon** [FoonieMagus/ApeironBattleDemo_IssueList#124]
### Demo Environment

Beta Test

### Battle Demo Version

V0.5.186

### System Environment

os: window 11 pro os , english os , AMD Ryzen 7 2700x Eight-Core Processor 3.90GHz 

### What is expected?

hopefully to remove the bug that can't aiming when released the skill of Fire c6 the volcano exists . it shouldn't be effect to myself when i use this skill

### What is happening?

all aiming is not aim able when i use FC6 the volcano exists .

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/issues?q=label%3Abug) to ensure this bug has not already been reported

### No personal information provided

- [X] I confirm that I have not provided any personal information such as my wallet address or email address in this contribution.

### Open ticket if needed

- [X] In the event that personal information is required, I understand that I am expected to open a ticket in the [Discord](https://discord.gg/apeiron-doodaria) channel and reference the specific issue on Github.

**Comment by gemscng** [comment]
it is defined as terrain which affect the skill casting
