### ISSUE TITLE
[🐛 Bug Report]: EC6 damage bug

### ISSUE THREAD

**Issue by tanbod** [FoonieMagus/ApeironBattleDemo_IssueList#127]
### Demo Environment

Production

### Battle Demo Version

0.5.186

### System Environment

Device name LAPTOP-PQL4Q8OR
Processor 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz 2.30 GHz
Installed RAM 32.0 GB (31.8 GB usable)
Device ID 960547AC-A53F-4F30-922C-6C6E35012C91
Product ID 00327-35933-61019-AAOEM
System type 64-bit operating system, x64-based processor
windows 10

### What is expected?

![image](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/assets/157596102/7819dc86-f5f4-4a89-9fbf-101442f57e2a)
EC6 full upgrade have 500% value
in my video my avatar have WP4 passive 18% more int
454int+18%=535int 
535int 500% = 2678.6 damage
avatar 350 RES reduce damage around 32%
2678.6 - 32% = 1,821 damage

### What is happening?

![image](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/assets/157596102/6808abfd-a210-4877-a16d-6d274ed9e03e)
EC6 full upgrade deal 1335 damage

### Reproducible Bugs

everytime

### Related link

https://drive.google.com/file/d/1ocAsMhC5FPOBTbFC0RDZdFVUt-4ztwWD/view?usp=sharing

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/issues?q=label%3Abug) to ensure this bug has not already been reported

### No personal information provided

- [X] I confirm that I have not provided any personal information such as my wallet address or email address in this contribution.

### Open ticket if needed

- [X] In the event that personal information is required, I understand that I am expected to open a ticket in the [Discord](https://discord.gg/apeiron-doodaria) channel and reference the specific issue on Github.

**Comment by gemscng** [comment]
different unit has different res.  Also 350 res, the damage reduction should be  1-500/(350+500), which is 41.2%

**Comment by tanbod** [comment]
in this video damage that deal to avatar is 1335
avatar res is 350 so it 41.2% reduction so it damage should be
535int 500% = 2678.6 damage - 41.2% reduction
so damage should be 1,575 
while damage it deal is 1335 is lower than the calculation right

**Comment by gemscng** [comment]
as discussed. it is WP4 bug. Refer to #129
