### ISSUE TITLE
[🐛 Bug Report]: avatar cant continue to auto attack after be black holed by Bood mage

### ISSUE THREAD

**Issue by Pewqqz** [FoonieMagus/ApeironBattleDemo_IssueList#16]
### Battle Demo Version

x0.3.8

### Environment

Mac M1

### What is expected?

can normally continue to auto attack after be black holed by bood mage.

### What is happening?

avatar cant continue to auto attack after be black holed by Bood mage

### Reproducible Bugs

100% occer in 1-2

### Additional info

have to dash in order to fix this prob

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/issues?q=label%3Abug) to ensure this bug has not already been reported

### No personal information provided

- [X] I confirm that I have not provided any personal information such as my wallet address or email address in this contribution.

### Open ticket if needed

- [X] In the event that personal information is required, I understand that I am expected to open a ticket in the [Discord](https://discord.gg/apeironnft) channel and reference the specific issue on Github.

**Comment by gemscng** [comment]
https://user-images.githubusercontent.com/7820794/218405839-5e41dc83-da6d-488c-a3cb-1de1ac36a3ed.mov

**Comment by emberwaynek** [comment]
fixed on 0ad13cc5cd70432cd4f0f8d7f552a7d937486d5d

**Comment by gemscng** [comment]
fixed in season2
