### ISSUE TITLE
[🐛 Bug Report]: Marketplace Leaderboard Ranking Bug

### ISSUE THREAD

**Issue by cxheng315** [FoonieMagus/ApeironBattleDemo_IssueList#17]
### Battle Demo Version

v0.3.8

### Environment

OS: Windwow 11 Pro
OS Language: English
Display Card: NVIDIA GeForce RTX 3070 Ti Laptop GPU
CPU: 12th Gen Intel(R) i9-12900H

### What is expected?

The leaderboard should display the correct ranking of the players, without any blank or missing entries.

### What is happening?

The leaderboard is displaying incorrect rankings, with some entries being blank or missing. Upon scrolling up a bit after reaching the bottom of the leaderboard, the error becomes visible.
<img width="655" alt="bottom" src="https://user-images.githubusercontent.com/64959125/217589753-b0b85aef-bcee-45ae-9259-eb70a8a8d073.png">
<img width="660" alt="up" src="https://user-images.githubusercontent.com/64959125/217589762-6ff27c10-5004-4c3e-8293-ea41fc63e559.png">

### Reproducible Bugs

Steps to Reproduce:

1. Scroll to the bottom of the leaderboard.
2. Scroll up a bit.
3. The incorrect display of the leaderboard rankings will be visible.

### Related link

https://marketplace.apeironnft.com/battle/demo/leaderboard/

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/issues?q=label%3Abug) to ensure this bug has not already been reported

### No personal information provided

- [X] I confirm that I have not provided any personal information such as my wallet address or email address in this contribution.

### Open ticket if needed

- [X] In the event that personal information is required, I understand that I am expected to open a ticket in the [Discord](https://discord.gg/apeironnft) channel and reference the specific issue on Github.

**Comment by gemscng** [comment]
@cxheng315  Should be fixed. Please verify

**Comment by cxheng315** [comment]
Resolved
