### ISSUE TITLE
[🐛 Bug Report]: Network error if you finish a dungeon and you click pause

### ISSUE THREAD

**Issue by BossOppa9208** [FoonieMagus/ApeironBattleDemo_IssueList#19]
### Battle Demo Version

v0.3.11

### Environment

OS: Windows 10
OS Language: English
NVIDIA GeForce GTX 1650
AMD Ryzen 5 2600 Sic-Core Processor

### What is expected?

Should not get network error

### What is happening?

Network error 

### Reproducible Bugs

Step 1: Finish a Dungeon
Step 2: Click the pause button before it disappears

![network error if you finish a dungeon and you click pause](https://user-images.githubusercontent.com/124492484/218091398-e85e8298-12eb-4d46-8a41-954d989c9e04.jpg)

### Related link

https://we.tl/t-cCk9yF3wSW

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/issues?q=label%3Abug) to ensure this bug has not already been reported

### No personal information provided

- [X] I confirm that I have not provided any personal information such as my wallet address or email address in this contribution.

### Open ticket if needed

- [X] In the event that personal information is required, I understand that I am expected to open a ticket in the [Discord](https://discord.gg/apeironnft) channel and reference the specific issue on Github.

**Comment by gemscng** [comment]
@BossOppa9208  Please verify and close if resolved. thanks

**Comment by BossOppa9208** [comment]
Verified!
