### ISSUE TITLE
[🐛 Bug Report]: Immortal Bood

### ISSUE THREAD

**Issue by MarkL-0** [FoonieMagus/ApeironBattleDemo_IssueList#2]
### What is expected?

Bood expected to die already

### What is actually happening?

The bood never died even after minutes of trying to kill it.

### Related link

https://youtu.be/yN7Idz49Ymk

### Environment

Windows 10 Pro, Lenovo ThinkPad Laptop Intel i7, 16GB RAM, Intel Iris XE graphics

### This is not a duplicated issue

- [X] #4

### No personal information provided

- [X] I confirm that I have not provided any personal information such as my wallet address or email address in this contribution.

### Open ticket if needed

- [X] In the event that personal information is required, I understand that I am expected to open a ticket in the [Discord](https://discord.gg/apeiron-doodaria) channel and reference the specific issue on Github.

**Comment by gemscng** [comment]
https://user-images.githubusercontent.com/7820794/218637947-5a1f8077-7515-45b4-b44a-3e64688805f1.mp4

From Im4
