### ISSUE TITLE
[🐛 Bug Report]: Network error in Shop

### ISSUE THREAD

**Issue by BossOppa9208** [FoonieMagus/ApeironBattleDemo_IssueList#20]
### Battle Demo Version

v0.3.11

### Environment

OS: Windows 10
OS Language: English
NVIDIA GeForce GTX 1650
AMD Ryzen 5 2600 Sic-Core Processor

### What is expected?

Should not get network error

### What is happening?

getting network error

### Reproducible Bugs

Step 1: Go to shop
Step 2: Exit shop and buy an item before it actually disappears.

### Related link

https://we.tl/t-NhvDFBIxFW

### Additional info

![image](https://user-images.githubusercontent.com/124492484/218327703-102a758c-0258-405a-b82d-482f9c56e9b4.png)

https://we.tl/t-NhvDFBIxFW

Found this bug coz sometimes I clicked the back button before buying and instinctively click the potion before the screen goes back to the main menu to atleast be able to buy something.

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/issues?q=label%3Abug) to ensure this bug has not already been reported

### No personal information provided

- [X] I confirm that I have not provided any personal information such as my wallet address or email address in this contribution.

### Open ticket if needed

- [X] In the event that personal information is required, I understand that I am expected to open a ticket in the [Discord](https://discord.gg/apeironnft) channel and reference the specific issue on Github.

**Comment by gemscng** [comment]
Fixed in 0.3.13.  @BossOppa9208  Please verify and close if resolved. thanks
