### ISSUE TITLE
[🐛 Bug Report]: Can't click the dungeon bug

### ISSUE THREAD

**Issue by BossOppa9208** [FoonieMagus/ApeironBattleDemo_IssueList#22]
### Battle Demo Version

v0.3.11

### Environment

OS: Windows 10
OS Language: English
NVIDIA GeForce GTX 1650
AMD Ryzen 5 2600 Sic-Core Processor

### What is expected?

Should be able to click.

### What is happening?

Can't click a dungeon, but the other buttons are fine.

### Reproducible Bugs

Yes, this is my 2nd time for this bug.
![image](https://user-images.githubusercontent.com/124492484/218405345-2e7fad1c-f753-4f99-9944-f7460a8a31cc.png)

### Related link

https://we.tl/t-gtLrvQB0yQ

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/issues?q=label%3Abug) to ensure this bug has not already been reported

### No personal information provided

- [X] I confirm that I have not provided any personal information such as my wallet address or email address in this contribution.

### Open ticket if needed

- [X] In the event that personal information is required, I understand that I am expected to open a ticket in the [Discord](https://discord.gg/apeironnft) channel and reference the specific issue on Github.

**Comment by gemscng** [comment]
#12
