### ISSUE TITLE
[🐛 Bug Report]: Only 1 apostle died but it shows 2 died when the stage ended

### ISSUE THREAD

**Issue by BossOppa9208** [FoonieMagus/ApeironBattleDemo_IssueList#23]
### Battle Demo Version

v0.3.11

### Environment

OS: Windows 10
OS Language: English
NVIDIA GeForce GTX 1650
AMD Ryzen 5 2600 Sic-Core Processor

### What is expected?

It should only show that 1 rouge died.

### What is happening?

It's showing 2 rogue died after the stage.

### Reproducible Bugs

I think so.

### Related link

https://we.tl/t-BP73jlEGF7

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/issues?q=label%3Abug) to ensure this bug has not already been reported

### No personal information provided

- [X] I confirm that I have not provided any personal information such as my wallet address or email address in this contribution.

### Open ticket if needed

- [X] In the event that personal information is required, I understand that I am expected to open a ticket in the [Discord](https://discord.gg/apeironnft) channel and reference the specific issue on Github.

**Comment by gemscng** [comment]
the last mage blackhole killed your rogue after the victory screen showed. I think this is expected for the current version
