### ISSUE TITLE
[🐛 Bug Report]: Loading Bug

### ISSUE THREAD

**Issue by MarkL-0** [FoonieMagus/ApeironBattleDemo_IssueList#24]
### Battle Demo Version

v0.3.13

### Environment

Win10 Pro
English
Ryzen 9 5950X
NVIDIA GeForce RTX 3080

### What is expected?

Reload the game

### What is happening?

Didn't reload and just continue the loading icon.

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/issues?q=label%3Abug) to ensure this bug has not already been reported

### No personal information provided

- [X] I confirm that I have not provided any personal information such as my wallet address or email address in this contribution.

### Open ticket if needed

- [X] In the event that personal information is required, I understand that I am expected to open a ticket in the [Discord](https://discord.gg/apeiron-doodaria) channel and reference the specific issue on Github.

**Comment by gemscng** [comment]
@MarkL-0  please also submit the video
