### ISSUE TITLE
[🐛 Bug Report]: Visual Bug on Victory Time 

### ISSUE THREAD

**Issue by BossOppa9208** [FoonieMagus/ApeironBattleDemo_IssueList#27]
### Battle Demo Version

v0.3.13

### Environment

OS: Windows 11
OS Language: English
NVIDIA GeForce GTX 1650
AMD Ryzen 5 2600 Sic-Core Processor

### What is expected?

I'm not sure what's the correct victory time.

### What is happening?

It's showing different victory time when you restart a battle and finish it at the same way you do without restarting.

25 seconds without restart
22 seconds with restart

### Reproducible Bugs

Yes

### Additional info

https://we.tl/t-erAimHo43d

https://we.tl/t-erAimHo43d

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/issues?q=label%3Abug) to ensure this bug has not already been reported

### No personal information provided

- [X] I confirm that I have not provided any personal information such as my wallet address or email address in this contribution.

### Open ticket if needed

- [X] In the event that personal information is required, I understand that I am expected to open a ticket in the [Discord](https://discord.gg/apeironnft) channel and reference the specific issue on Github.

**Comment by gemscng** [comment]
Not valid for latest version
