### ISSUE TITLE
[🐛 Bug Report]: Dep 3-9 Archer no attack animation and 990 dmg

### ISSUE THREAD

**Issue by BossOppa9208** [FoonieMagus/ApeironBattleDemo_IssueList#28]
### Battle Demo Version

v0.3.13

### Environment

OS: Windows 11
OS Language: English
NVIDIA GeForce GTX 1650
AMD Ryzen 5 2600 Sic-Core Processor

### What is expected?

The bood archer should have an attack animation and I think it should not deal that high damage.

### What is happening?

The last wave has a Bood archer that has no attack animation and it deals 990 dmg. 

### Reproducible Bugs

![Dep 3-9 Archer no attack animation and 990 dmg](https://user-images.githubusercontent.com/124492484/224534425-5a1b2a0c-ca2e-4aa2-afeb-9f3ba4794f12.jpg)

It's my first time fighting Dep 3-9 Elite but I think it's reproducible.

### Related link

https://we.tl/t-7uDVe4LAhc

### Additional info

https://we.tl/t-7uDVe4LAhc

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/issues?q=label%3Abug) to ensure this bug has not already been reported

### No personal information provided

- [X] I confirm that I have not provided any personal information such as my wallet address or email address in this contribution.

### Open ticket if needed

- [X] In the event that personal information is required, I understand that I am expected to open a ticket in the [Discord](https://discord.gg/apeironnft) channel and reference the specific issue on Github.

**Comment by gemscng** [comment]
It has super slow attack speed so it is intended. And the high damage too.

**Comment by BossOppa9208** [comment]
I see.
