### ISSUE TITLE
[🐛 Bug Report]: doesn't receive the apostles after claiming in the stage resulting site

### ISSUE THREAD

**Issue by Pewqqz** [FoonieMagus/ApeironBattleDemo_IssueList#34]
### Demo Environment

Beta Test

### Battle Demo Version

v0.4.20

### System Environment

MacAir M1

### What is expected?

receive apostle properly

### What is happening?

dont receive the apostle shown in stage resulting site (It happens very often)

### Reproducible Bugs

dont know actually how to reproduce it. but it happens like 30-40% for me when claim the apostle from the stages

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/issues?q=label%3Abug) to ensure this bug has not already been reported

### No personal information provided

- [X] I confirm that I have not provided any personal information such as my wallet address or email address in this contribution.

### Open ticket if needed

- [X] In the event that personal information is required, I understand that I am expected to open a ticket in the [Discord](https://discord.gg/apeironnft) channel and reference the specific issue on Github.

**Comment by gemscng** [comment]
@Pewqqz  this should be solve in 0.4.25, please verify. Thanks.

**Comment by Pewqqz** [comment]
yeh it seems to be solved
