### ISSUE TITLE
[🐛 Bug Report]: Rogue Apostle enemy he simply stands still and does not attack

### ISSUE THREAD

**Issue by Megalo5** [FoonieMagus/ApeironBattleDemo_IssueList#59]
### Demo Environment

Beta Test

### Battle Demo Version

v0.3.8

### System Environment

OS: Windows 10
Language: Portuguese
AMD Athlon 300g with Radeon Vega Graphics
8GB RAM

### What is expected?

enemy rogue apostle moves and attack

### What is happening?

he doesn't move, nor does he attack or use his abilities

### Additional info

I want to report the bug that frequently occurs with me.

It's about the enemy Rogue apostle, almost every time I play PvE mode, in certain battles, when the Rogue appears after I've defeated the other enemies, it just stands still, not attacking or using its abilities!

Because of this, I can easily win the battle, which takes away some of the excitement.

I appreciate it if you can resolve this bug.

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/issues?q=label%3Abug) to ensure this bug has not already been reported

### No personal information provided

- [X] I confirm that I have not provided any personal information such as my wallet address or email address in this contribution.

### Open ticket if needed

- [X] In the event that personal information is required, I understand that I am expected to open a ticket in the [Discord](https://discord.gg/apeiron-doodaria) channel and reference the specific issue on Github.

**Comment by gemscng** [comment]
please provide a video.
