### ISSUE TITLE
[🐛 Bug Report]: Undying bug 

### ISSUE THREAD

**Issue by gemscng** [FoonieMagus/ApeironBattleDemo_IssueList#60]
### Demo Environment

Beta Test

### Battle Demo Version

v0.5.104

### System Environment

UNknown

### What is expected?

Avatar die

### What is happening?

from @ tanbodtan 
bug i die but game wont end
![image](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/assets/7820794/8e76c5fe-0ab0-4d8e-945d-62fb30cb7fbf)

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/issues?q=label%3Abug) to ensure this bug has not already been reported

### No personal information provided

- [X] I confirm that I have not provided any personal information such as my wallet address or email address in this contribution.

### Open ticket if needed

- [X] In the event that personal information is required, I understand that I am expected to open a ticket in the [Discord](https://discord.gg/apeiron-doodaria) channel and reference the specific issue on Github.

**Comment by Mirage1233** [comment]
Oponents disconected but have victory without fight
in 2 round i win but figh not stop and red zone kill me too)
![Знімок екрана (89)](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/assets/157888006/12aa56c2-db98-4f00-b118-a216ffe40000)
![Знімок екрана (90)](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/assets/157888006/0b6b9b22-021f-4453-83e9-1b458f0ab8aa)

**Comment by ryze534** [comment]
Undying bug. There is video down below.
https://youtu.be/GVlagoQ9UJM?si=GJLmScUEpLTFw7Ku

**Comment by gemscng** [comment]
@ryze534  what is your device spec?

**Comment by ryze534** [comment]
![螢幕擷取畫面 2024-01-29 194223](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/assets/130861952/ff125172-231f-4ebe-8f95-e91c0856b212)
![螢幕擷取畫面 2024-01-29 194330](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/assets/130861952/b34bfee9-d054-4478-a401-8100b81791b5)

![螢幕擷取畫面 2024-01-29 194349](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/assets/130861952/81fe9704-669f-4b93-a198-1f0e0cbd0728)
