### ISSUE TITLE
[🐛 Bug Report]:  Winstreak not showing.

### ISSUE THREAD

**Issue by 0xRufka** [FoonieMagus/ApeironBattleDemo_IssueList#61]
### Demo Environment

Production

### Battle Demo Version

5.110

### System Environment

Windows 11 

### What is expected?

Winstreak not showing.

### What is happening?

Winstreak not showing. Its showing onlu when u click apostle, then confrim, and it can be shown for ~1 sec, then dissapeers again.

### Related link

https://www.youtube.com/watch?v=GZtKk2yYc48

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/issues?q=label%3Abug) to ensure this bug has not already been reported

### No personal information provided

- [X] I confirm that I have not provided any personal information such as my wallet address or email address in this contribution.

### Open ticket if needed

- [X] In the event that personal information is required, I understand that I am expected to open a ticket in the [Discord](https://discord.gg/apeironnft) channel and reference the specific issue on Github.

**Comment by gemscng** [comment]
Remember to give it a title

**Comment by gemscng** [comment]
fixed in 0.5.112. Please verify.

**Comment by 0xRufka** [comment]
ye now all working ! thx gj
