### ISSUE TITLE
[🐛 Bug Report]: Clicking Skill Tree Resets Skills

### ISSUE THREAD

**Issue by MisterBanatero** [FoonieMagus/ApeironBattleDemo_IssueList#64]
### Demo Environment

Beta Test

### Battle Demo Version

v0.5.110

### System Environment

![image](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/assets/157146980/3e5de38b-a5fd-4043-ac14-07995c1d8b0c)
![image](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/assets/157146980/efd9640e-094f-4972-a81b-4d3e5a0a494b)

### What is expected?

It is expected to retain the skills when you click the skill tree if you want to edit it. It is really annoying to add skills again.

### What is happening?

Whenever you click the skill tree on the side, it will reset the current avatar skills.
From this
![image](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/assets/157146980/43eb1ea1-27ad-40aa-b699-ba37824dc3ca)
To this
![image](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/assets/157146980/3d27755c-28a2-4732-beed-68db84e3c3c7)

### Reproducible Bugs

Click the skill tree on the side, it will reset the current avatar skills.
![image](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/assets/157146980/43eb1ea1-27ad-40aa-b699-ba37824dc3ca)

### Related link

https://youtu.be/OL97mNNbXqU

### Additional info

You can view it in my youtube link, just go to 1:03:53

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/issues?q=label%3Abug) to ensure this bug has not already been reported

### No personal information provided

- [X] I confirm that I have not provided any personal information such as my wallet address or email address in this contribution.

### Open ticket if needed

- [X] In the event that personal information is required, I understand that I am expected to open a ticket in the [Discord](https://discord.gg/apeiron-doodaria) channel and reference the specific issue on Github.

**Comment by gemscng** [comment]
More sample
https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/assets/7820794/c54373e4-8927-4681-b8f6-a040450eb9b9
