### ISSUE TITLE
[🐛 Bug Report]: lags in pvp mode Apeiron

### ISSUE THREAD

**Issue by Pepecrazy** [FoonieMagus/ApeironBattleDemo_IssueList#67]
### Demo Environment

Beta Test

### Battle Demo Version

v0.5.112

### System Environment

windows 10, AMD Ryzen 5 5600G with Radeon Graphics

### What is expected?

i expected to play pvp in Apeiron :)

### What is happening?

some problem maybe with latency or i don't know (my internet is good, pve mode Apeiron was smooth)

### Reproducible Bugs

all in video

### Related link

https://youtu.be/tfON1yvi7TY

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/issues?q=label%3Abug) to ensure this bug has not already been reported

### No personal information provided

- [X] I confirm that I have not provided any personal information such as my wallet address or email address in this contribution.

### Open ticket if needed

- [X] In the event that personal information is required, I understand that I am expected to open a ticket in the [Discord](https://discord.gg/apeironnft) channel and reference the specific issue on Github.

**Comment by gemscng** [comment]
@Pepecrazy  is this happending every match?

**Comment by Pepecrazy** [comment]
> @Pepecrazy is this happending every match?

yes, every match

**Comment by Pepecrazy** [comment]
> @Pepecrazy is this happending every match?
@gemscng

also i noticed very big delays in menu pve mode (click on map or quest answer/etc and then waiting 5-20+ seconds for respond), but in the pve match all is fine

**Comment by gemscng** [comment]
@Pepecrazy  The display card seems not able to run the game smoothly. You will need to upgrade the card or wait for mobile version.  Reference
https://www.videocardbenchmark.net/compare/4406vs4045vs4117/Ryzen-5-5600G-with-Radeon-Graphics-vs-GeForce-GTX-1660-Ti-vs-GeForce-RTX-2060-SUPER

**Comment by Pepecrazy** [comment]
@gemscng message above

**Comment by gemscng** [comment]
Existing FPS display is not correct. Also, non battle screen normally is only 1/10 of the workload in a battle scene, so you can run in non battle screen do not mean your display card can run the game

**Comment by Pepecrazy** [comment]
> @gemscng

@gemscng now playing pvp without issues, so there probably was problem in servers not iGPU
