### ISSUE TITLE
[🐛 Bug Report]: Enemies do not move in bot combat

### ISSUE THREAD

**Issue by doriton** [FoonieMagus/ApeironBattleDemo_IssueList#69]
### Demo Environment

Production

### Battle Demo Version

v0.5.112

### System Environment

Operating System: Windows 11 Home 64-bit Japanese NVIDIA GeForce RTX 3050 Ti Laptop GPU 11th Gen Intel(R) Core(TM) i7-11800H

### What is expected?

When they get out of range, they become sticking

### What is happening?

When they get out of range, they become sticking

### Reproducible Bugs

yes

### Related link

https://youtu.be/BTZwSizOjK4

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/issues?q=label%3Abug) to ensure this bug has not already been reported

### No personal information provided

- [X] I confirm that I have not provided any personal information such as my wallet address or email address in this contribution.

### Open ticket if needed

- [X] In the event that personal information is required, I understand that I am expected to open a ticket in the [Discord](https://discord.gg/apeironnft) channel and reference the specific issue on Github.

**Comment by gemscng** [comment]
@doriton  this is expected behavior for practice bot now. We use have more advance boot in the future
