### ISSUE TITLE
[🐛 Bug Report]: Fire C5 instant overwheming burn

### ISSUE THREAD

**Issue by Pewqqz** [FoonieMagus/ApeironBattleDemo_IssueList#73]
### Demo Environment

Beta Test

### Battle Demo Version

v0.5.122

### System Environment

------------
      Time of this report: 5/26/2023, 01:19:48
             Machine name: DESKTOP-3AI0EJS
               Machine Id: {B69F230F-A4DC-45EC-BCD3-E47D428503D3}
         Operating System: Windows 10 Pro 64-bit (10.0, Build 19045) (19041.vb_release.191206-1406)
                 Language: English (Regional Setting: English)
      System Manufacturer: ASUS
             System Model: System Product Name
                     BIOS: 0820 (type: UEFI)
                Processor: 11th Gen Intel(R) Core(TM) i5-11400F @ 2.60GHz (12 CPUs), ~2.6GHz
                   Memory: 16384MB RAM
      Available OS Memory: 16222MB RAM
                Page File: 17759MB used, 12285MB available
              Windows Dir: C:\WINDOWS
          DirectX Version: DirectX 12
      DX Setup Parameters: Not found
         User DPI Setting: 96 DPI (100 percent)
       System DPI Setting: 96 DPI (100 percent)

### What is expected?

not this too much damage from Fire C5

### What is happening?

Fire C5 burn too much damage

https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/assets/88717536/271d0d42-3342-4552-bc91-92e9a8379c96

### Reproducible Bugs

?

### Related link

-

### Additional info

-

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/issues?q=label%3Abug) to ensure this bug has not already been reported

### No personal information provided

- [X] I confirm that I have not provided any personal information such as my wallet address or email address in this contribution.

### Open ticket if needed

- [X] In the event that personal information is required, I understand that I am expected to open a ticket in the [Discord](https://discord.gg/apeiron-doodaria) channel and reference the specific issue on Github.

**Comment by Pewqqz** [comment]
https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/assets/88717536/a6565cc8-4820-4dba-80f2-c8cde6fc87ff

**Comment by Pewqqz** [comment]
last round video

**Comment by Pewqqz** [comment]
maybe enemy's Fire C5 using when the game ends is the reason that leads to the bug in the lastest round

**Comment by gemscng** [comment]
@Pewqqz v0.5.124 should already fixed. please let us know if you have encounter it again.
