### ISSUE TITLE
[🐛 Bug Report]: Card stuck on the cursor, skills isn't exposed and can't use any skills either. can only walk on PvP, happened on 2nd round

### ISSUE THREAD

**Issue by betW3GG** [FoonieMagus/ApeironBattleDemo_IssueList#79]
### Demo Environment

Beta Test

### Battle Demo Version

v0.5.124

### System Environment

OS: Windows 10 Home Single language 64 Bit
System Model: ASUS TUF Dash F15 FX516PM
Processor: 11th Gen Intel Core i7-11370H @3.30Hz (~8 CPUs)
Memory: 16GB RAM
![image](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/assets/157984257/3f85a028-e22d-4e95-be71-4db8d8323292)
![image](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/assets/157984257/4b956c9f-4148-489c-b379-dece3d6693e7)

### What is expected?

2nd round of the match going well or smoothly

### What is happening?

i clicked on either of the cards when i'm still loading into the 2nd match, and then the card is stuck onto my cursor. after the 2nd match started i can't even click on any of the card skills

### Reproducible Bugs

i don't really know how to reproduce the bug, but you can try to click or hold any skill card when you're loading into the 2nd match and see if it'll have the same bug or not
or
you can hold on a card when an apostle was about to die on the 1st match (?)

### Related link

https://youtu.be/YEAhch_JYR0

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/issues?q=label%3Abug) to ensure this bug has not already been reported

### No personal information provided

- [X] I confirm that I have not provided any personal information such as my wallet address or email address in this contribution.

### Open ticket if needed

- [X] In the event that personal information is required, I understand that I am expected to open a ticket in the [Discord](https://discord.gg/apeiron-doodaria) channel and reference the specific issue on Github.

**Comment by gemscng** [comment]
@betW3GG is there a video before it happen?

**Comment by betW3GG** [comment]
> @betW3GG is there a video before it happen?

unfortunately, no. this is my 1st time experiencing this kind of bug. and i started my recording when i realized that i got a bug

**Comment by gemscng** [comment]
should fixed in 0.5.139 @betW3GG
