### ISSUE TITLE
[🐛 Bug Report]:  avatar dies at same time 

### ISSUE THREAD

**Issue by OHC31** [FoonieMagus/ApeironBattleDemo_IssueList#81]
### Demo Environment

Beta Test

### Battle Demo Version

v0.5.124 beta-serv ( PVP)

### System Environment

Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz   3.70 GHz
windows 10 

### What is expected?

my win \ draw

### What is happening?

Avatars dies at same time ( i think enemy die 1st)
When both avatars was dead, and I could still use my minions (archer) skills.
The game continues but nothing happens
Opponent disconnected and still nothing happens ( no win for me) 

### Reproducible Bugs

currently it happen when both avatar die ( almost same time)

### Related link

https://www.youtube.com/watch?v=PTzQ6YKskf8

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/issues?q=label%3Abug) to ensure this bug has not already been reported

### No personal information provided

- [X] I confirm that I have not provided any personal information such as my wallet address or email address in this contribution.

### Open ticket if needed

- [X] In the event that personal information is required, I understand that I am expected to open a ticket in the [Discord](https://discord.gg/apeiron-doodaria) channel and reference the specific issue on Github.

**Comment by gemscng** [comment]
Still happending in 0.5.139
