### ISSUE TITLE
[🐛 Bug Report]: The player started 2 matches against different opponents at once.

### ISSUE THREAD

**Issue by OHC31** [FoonieMagus/ApeironBattleDemo_IssueList#82]
### Demo Environment

Beta Test

### Battle Demo Version

v0.5.124 beta-serv ( PVP)

### System Environment

Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz 3.70 GHz
windows 10

### What is expected?

Beginning of the game

### What is happening?

I came across a player who at the same time was caught by another player (2 matches at the same time). This became clear when another player and I simultaneously wrote that we had come across a third player (because he is a YouTuber). As a result, all three players have an endless loading of the match.

### Reproducible Bugs

-

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/issues?q=label%3Abug) to ensure this bug has not already been reported

### No personal information provided

- [X] I confirm that I have not provided any personal information such as my wallet address or email address in this contribution.

### Open ticket if needed

- [X] In the event that personal information is required, I understand that I am expected to open a ticket in the [Discord](https://discord.gg/apeiron-doodaria) channel and reference the specific issue on Github.

**Comment by tanbod** [comment]
i met this one too with shadowsan the 3 person that get match with get a forever waiting for opponent
might be same issue as this one 
https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/issues/76
