### ISSUE TITLE
[🐛 Bug Report]: App closes iphone 11

### ISSUE THREAD

**Issue by 0xRufka** [FoonieMagus/ApeironBattleDemo_IssueList#90]
### Demo Environment

Beta Test

### Battle Demo Version

ios version

### System Environment

Iphone 11

### What is expected?

App closes

### What is happening?

App closes when i trying to change apostle/ when clicking on apostle. Sometimes it happening insta, sometimes on 2nd or 3d click on apostle. On video u can see it at the end

### Related link

https://youtube.com/shorts/680oWZAW98k?feature=share

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/issues?q=label%3Abug) to ensure this bug has not already been reported

### No personal information provided

- [X] I confirm that I have not provided any personal information such as my wallet address or email address in this contribution.

### Open ticket if needed

- [X] In the event that personal information is required, I understand that I am expected to open a ticket in the [Discord](https://discord.gg/apeiron-doodaria) channel and reference the specific issue on Github.

**Comment by yova22** [comment]
App close either iphone 12
