### ISSUE TITLE
[🐛 Bug Report]: Drag to the bottom make Hunter stuck inside the wall

### ISSUE THREAD

**Issue by taetae20s** [FoonieMagus/ApeironBattleDemo_IssueList#93]
### Demo Environment

Production

### Battle Demo Version

v0.5.139

### System Environment

OS: Window 10
OS Language: English
GTX 1050TI
AMD Ryzen 3 2200G

### What is expected?

My rogue attacking enemy's hunter apostle

### What is happening?

Opponent's hunter stuck into the wall and still shooting and trigger energize skill. My rouge is aggro by hunter and keep their face into the invisible wall

### Reproducible Bugs

Not sure about the method, but here's my theory
- Hunter's energize trigger and step backward through the wall (which impossible imo)
- Drag to the bottom hit the hunter in same direction twice
- Drag to the bottom hit the hunter while triggering energize skill into the wall direction

### Related link

https://youtu.be/vesNi1uilHE

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/issues?q=label%3Abug) to ensure this bug has not already been reported

### No personal information provided

- [X] I confirm that I have not provided any personal information such as my wallet address or email address in this contribution.

### Open ticket if needed

- [X] In the event that personal information is required, I understand that I am expected to open a ticket in the [Discord](https://discord.gg/apeiron-doodaria) channel and reference the specific issue on Github.

**Comment by rango-ember** [comment]
fixed at 93f341b
might need more tests
