### ISSUE TITLE
[🐛 Bug Report]: Wind P4 static charge delay before take effect

### ISSUE THREAD

**Issue by tanbod** [FoonieMagus/ApeironBattleDemo_IssueList#94]
### Demo Environment

Beta Test

### Battle Demo Version

5.139

### System Environment

Device name LAPTOP-PQL4Q8OR
Processor 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz 2.30 GHz
Installed RAM 32.0 GB (31.8 GB usable)
Device ID 960547AC-A53F-4F30-922C-6C6E35012C91
Product ID 00327-35933-61019-AAOEM
System type 64-bit operating system, x64-based processor
windows 10

### What is expected?

![Untitled](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/assets/157596102/15fd0fdf-06d2-42da-82f4-31d342e31432)
shock wave should occur when avatar reach max distant dash

### What is happening?

after avatar dash reach max distant a short delay will occur before the shock wave is sending out

### Reproducible Bugs

every time 

### Related link

https://drive.google.com/drive/folders/10NK1KGJpZ5kitSWK46R-xmTs5yFkpy_c?usp=drive_link

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/issues?q=label%3Abug) to ensure this bug has not already been reported

### No personal information provided

- [X] I confirm that I have not provided any personal information such as my wallet address or email address in this contribution.

### Open ticket if needed

- [X] In the event that personal information is required, I understand that I am expected to open a ticket in the [Discord](https://discord.gg/apeiron-doodaria) channel and reference the specific issue on Github.

**Comment by EmberLeung** [comment]
The Perk effect is trigger at 1.5s after dash

**Comment by EmberLeung** [comment]
We will update the description add information for 1.5s delay.

**Comment by gemscng** [comment]
this should be fixed in 0.5.157
