### ISSUE TITLE
[🐛 Bug Report]: Can't play PVP. No Energy and other info in the upper right for PVP home page.

### ISSUE THREAD

**Issue by MarkL-0** [FoonieMagus/ApeironBattleDemo_IssueList#97]
### Demo Environment

Production

### Battle Demo Version

v0.5.145win

### System Environment

OS: Windows 11 Pro
AMD Ryzen 9 5950x
NVDIA GeForce RTX 3080

### What is expected?

Loading should complete and the energy should come out.

### What is happening?

Loading endlessly. The energy and other info in the upper right does not show.

### Reproducible Bugs

Every time I open my account, it does this. When I opened with guest account, the problem goes away. When I used mine again, still doing the same thing.

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/issues?q=label%3Abug) to ensure this bug has not already been reported

### No personal information provided

- [X] I confirm that I have not provided any personal information such as my wallet address or email address in this contribution.

### Open ticket if needed

- [X] In the event that personal information is required, I understand that I am expected to open a ticket in the [Discord](https://discord.gg/apeiron-doodaria) channel and reference the specific issue on Github.

**Comment by MarkL-0** [comment]
![Energy Missing Bug](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/assets/124481507/43f52696-d420-4622-8725-8b0f45ddb433)

**Comment by gemscng** [comment]
latest version should be 0.5.147
