### ISSUE TITLE
[🐛 Bug Report]: Error when starting a game after switching account from guest account with existing team

### ISSUE THREAD

**Issue by bikutaaaa** [FoonieMagus/ApeironBattleDemo_IssueList#98]
### Demo Environment

Production

### Battle Demo Version

v0.5.147

### System Environment

na

### What is expected?

Match will start and move to team setup

### What is happening?

error message

### Reproducible Bugs

yes
1. logout
2. login with different account or guest
3. queue find match

### Related link

na

### Additional info

na

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/issues?q=label%3Abug) to ensure this bug has not already been reported

### No personal information provided

- [X] I confirm that I have not provided any personal information such as my wallet address or email address in this contribution.

### Open ticket if needed

- [X] In the event that personal information is required, I understand that I am expected to open a ticket in the [Discord](https://discord.gg/apeiron-doodaria) channel and reference the specific issue on Github.

**Comment by gemscng** [comment]
@bikutaaaa  please add a vide

**Comment by bikutaaaa** [comment]
https://drive.google.com/file/d/1TdrF7QeSPIGPf_qlTNDWQA8-lTFIshbD/view?usp=sharing @gemscng

**Comment by gemscng** [comment]
@bikutaaaa  can you check if this has been solved in v0.5.157?

**Comment by bikutaaaa** [comment]
@gemscng confirm, error no longer occurs
