### ISSUE TITLE
[🐛 Bug Report]:  Enemy's avatar and apostle missing

### ISSUE THREAD

**Issue by 0xHungryJosh** [FoonieMagus/ApeironBattleDemo_IssueList#99]
### Demo Environment

Production

### Battle Demo Version

v0.5.147

### System Environment

OS: Windows 11
OS Language: English
Display Card: Gigabyte Aorus GTX 1070
CPU: Ryzen 5 2600

### What is expected?

When the game started my enemy's avatar and apostle should be there

### What is happening?

My enemy's avatar and apostle is missing

![image](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/assets/159259325/181544d1-dba9-4250-9bd3-5ef611e3ed5b)

![image](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/assets/159259325/3ffccad6-dcdc-4358-bae1-30195727dafe)

![image](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/assets/159259325/243b0829-7efd-4910-a60d-346df775376e)

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/issues?q=label%3Abug) to ensure this bug has not already been reported

### No personal information provided

- [X] I confirm that I have not provided any personal information such as my wallet address or email address in this contribution.

### Open ticket if needed

- [X] In the event that personal information is required, I understand that I am expected to open a ticket in the [Discord](https://discord.gg/apeiron-doodaria) channel and reference the specific issue on Github.

**Comment by gemscng** [comment]
It would be nice to provide a full screenshot or video
